### ISSUE TITLE
Error when passing binary string

### ISSUE THREAD

**Issue by jonag** [romainneutron/TwigExtension-DataUri#3]
I am facing an issue when I try to use this extension with binary string. I'm using the extension with Symfony2 and when I do this :

```html
<img src="{{ user.picture|dataUri(false) }}" class="img-circle" style="height: 25px"/>
```

this exception is thrown :

```
An exception has been thrown during the rendering of a template ("Warning: file_exists() expects parameter 1 to be a valid path, string given") in WorkUnit/table.html.twig at line 22.
```

I assume the issue comes from [this check](https://github.com/romainneutron/TwigExtension-DataUri/blob/master/src/DataURI/TwigExtension.php#L116) as a binary string doesn't seem to be a valid path (and when I comment this check it works well).

Unfortunately I'm not sure how to solve this so I can't make a PR...

**Comment by nico-incubiq** [comment]
+1 on this one. The error comes from [here](https://github.com/romainneutron/TwigExtension-DataUri/blob/master/src/DataURI/TwigExtension.php#L120). You may call ctype_print() before file_exists().
