### ISSUE TITLE
new  release

### ISSUE THREAD

**Issue by tubssp** [romainneutron/TwigExtension-DataUri#5]
Hello,

can you make a new release.
datauri 0.2 is the actual version and the release 0.1 from this twigextention reference to 0.1

**Comment by tubssp** [comment]
ping @romainneutron

**Comment by tubssp** [comment]
@romainneutron there is a problem with my desire to create a new stable release

**Comment by romainneutron** [comment]
Hello, I just released version 1.0.0 here https://github.com/romainneutron/TwigExtension-DataUri/releases/tag/1.0.0

Thanks for your patience
